### ISSUE TITLE
Migration to popper.js v2

### ISSUE THREAD

**Issue by mykas** [popperjs/react-popper#331] opened 2020-01-31 07:56 UTC
Dear @FezVrasta,

I see from the popper.js documentation that you managed to release version 2! 😱 This is amazing and thank you for all the hard work you did. Now talking about the `react-popper` library, do you have plans to update it too in near future? If not maybe I can do a contribution based on the migration guide.

**Comment by billyjanitsch** [comment] 2020-01-31 16:49
Duplicate of https://github.com/popperjs/react-popper/issues/328. 🙂

The author pointed to recent discussion in https://github.com/popperjs/react-popper/issues/241.

**Closed** 2020-01-31 17:25 UTC
